### ISSUE TITLE
Novas Imagens para Submissão de Atividades

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#1]
### Peça/publicidade solicitada
Basicamente, uma arte simples e expositivas das informações.

### Detalhamento do uso
Essa arte será destinada a intensificar as chamadas de trabalhos.

### Data prevista para uso da arte
Quinta-feira, 28/10/2021

### Quais informações devem aparecer na arte

Arte de Submissão de Palestras

(pt)
- https://conf.scipy.lat/
- 8ª Conferência Scipy Latam
- Seja um palestrante na Scipy Latam 2021. 📣❗
Submeta sua palestra hoje!
- Data Limite: 01/11/2021
-----------
(es)
- https://conf.scipy.lat/
- 8ª Conferencia Scipy Latam
- Se un ponente en Scipy Latam 2021. 📣❗
¡Envía tu propuesta hoy!
- Fecha Límite: 01/11/2021

Arte de Submissão de Tutoriais

- https://conf.scipy.lat/
- 8ª Conferência Scipy Latam
- Submeta seu tutorial para a Scipy Latam 2021!
- Data Limite: 01/11/2021
-----------
- https://conf.scipy.lat/
- 8ª Conferencia Scipy Latam
- Envíe su tutorial en Scipy Latam 2021! (es)
- Fecha Límite: 01/11/2021

### Quais formatos necessários
- [x] Quadrado
- [x] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre PyBR2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by lucenacam** [comment]
Submeta sua palestra - PT/BR

![Instagram_lembrete_pt](https://user-images.githubusercontent.com/84945537/139538068-f0b15b93-6f58-4cfb-ab93-982fdf9389f4.png)
![Stories_lembrete_pt](https://user-images.githubusercontent.com/84945537/139538071-2af51aee-9fdd-49ca-a751-688c254edb86.png)

**Comment by lucenacam** [comment]
Submeta sua palestra - ES

![Instagram_lembrete](https://user-images.githubusercontent.com/84945537/139538121-0f0da846-3efa-4122-9dc8-bf1612a7434d.png)
![Stories_lembrete](https://user-images.githubusercontent.com/84945537/139538122-3859ddd0-50ca-4349-9fb3-031218164c07.png)

**Comment by lucenacam** [comment]
Ainda dá tempo - ES

![Instagram_corre](https://user-images.githubusercontent.com/84945537/139539813-af683b04-7e27-46d6-aad2-2d05f7da0ba2.png)
![Stories_corre](https://user-images.githubusercontent.com/84945537/139539816-0c63f3c7-9941-4fd8-9d4d-5a02ca458b48.png)

**Comment by lucenacam** [comment]
Ainda dá tempo - PT/BR

![Instagram_corre_pt](https://user-images.githubusercontent.com/84945537/139539984-73dd8b0a-90cd-4750-8056-3312f87276d2.png)
![Stories_corre_pt](https://user-images.githubusercontent.com/84945537/139539987-e6e321d9-f16c-455c-a985-1ce0dfb33b8b.png)

**Comment by lucenacam** [comment]
Ainda dá tempo - PT/BR

![Stories_corre_pt](https://user-images.githubusercontent.com/84945537/139540040-a502112e-f694-4a4b-aafd-caf3a470b858.png)
![Instagram_corre_pt](https://user-images.githubusercontent.com/84945537/139540036-3b94d9e0-5f8b-4064-a860-5df6c137bd6e.png)

**Comment by lucenacam** [comment]
Envie seu Tutorial - ES

![Instagram_tutorial](https://user-images.githubusercontent.com/84945537/139543361-f3818634-72ec-4ccd-bd94-fe1f0e74e29d.png)
![Stories_tutorial](https://user-images.githubusercontent.com/84945537/139543365-f7cd055c-04d9-481b-9746-ab909069ea54.png)

**Comment by lucenacam** [comment]
Envie seu Tutorial - PT/BR

![Instagram_tutorial_pt](https://user-images.githubusercontent.com/84945537/139543389-9a9c3456-b391-4188-9a89-09d0c5957c8b.png)
![Stories_tutorial_pt](https://user-images.githubusercontent.com/84945537/139543392-d552632b-6b19-44d2-89f7-36a567eed2eb.png)

**Comment by lucenacam** [comment]
Envie seu Tutorial - PT/BR

![Instagram_tutorial_pt](https://user-images.githubusercontent.com/84945537/139543521-34a66c4c-c8c3-4014-8f49-e87e5df96980.png)
![Stories_tutorial_pt](https://user-images.githubusercontent.com/84945537/139543523-93a1781c-cfa7-488c-910f-1dd731ec381d.png)

**Comment by arthuralvim** [comment]
Submissão de palestras enviadas!

**Comment by arthuralvim** [comment]
Postagens do fusquinha enviadas!
Fechando a issue já que todas as artes foram usadas!

**Comment by lucenacam** [comment]
![Instagram_corra_novo_pt](https://user-images.githubusercontent.com/84945537/141017563-41250e37-d20d-427a-b58c-b7ddac5495ba.png)
![Instagram_corra_novo](https://user-images.githubusercontent.com/84945537/141017577-d6231cee-ae09-47d0-9b44-1a1b089545c4.png)

**Comment by lucenacam** [comment]
![Stories_corra_novo_pt](https://user-images.githubusercontent.com/84945537/141017828-d1fc7062-37bc-4583-81cf-709c7637e561.png)
![Stories_corre_novo](https://user-images.githubusercontent.com/84945537/141017843-ffbbf2d3-c714-4984-9049-8f99edebc209.png)
