### ISSUE TITLE
Postagem para Publicação da Grade de Programação

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#10]
### Peça/publicidade solicitada
Postagem para Publicação da Grade de Programação

### Quais informações devem aparecer na arte
(pt-br)

- Grade de Programação Publicada
- https://conf.scipy.lat/

- TEXTO DAS POSTAGENS: 
Grade de programação publicada! 
Tem muito conteúdo bom! Vem cá dar uma conferida: https://conf.scipy.lat/grade-programacao/
Hora de compartilhar está ótima notícia com os amigos pythonistas e espalhar a boa nova!
------------
(es)

- Programa publicado
- https://conf.scipy.lat/

- TEXTO DAS POSTAGENS: 

¡Programa publicado!
¡Tiene mucho contenido bueno! Ven a verlo: https://conf.scipy.lat/grade-programacao/
¡Es hora de compartir esta gran noticia con amigos pythonistas y difundir la buena noticia!

### Data prevista para uso da arte
22/11/2021

### Quais formatos necessários
- [x] Quadrado
- [x] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre ScipyLat2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by lucenacam** [comment]
![Stories_Palestrantes_ES](https://user-images.githubusercontent.com/84945537/144146138-0272ac1a-517e-4e75-a036-05825472690a.png)
![Stories_Palestrantes](https://user-images.githubusercontent.com/84945537/144146149-1b967e41-f0ab-43b5-b6ad-6bb5b2fd464d.png)

**Comment by lucenacam** [comment]
![Palestrantes ES](https://user-images.githubusercontent.com/84945537/144146509-88110096-f0d5-4350-a72f-521bab4e925c.png)
![Stories_Palestrantes_ES](https://user-images.githubusercontent.com/84945537/144146518-f4cb2dd6-fffc-4474-b9ab-c32a4277cdc4.png)
![Stories_Palestrantes](https://user-images.githubusercontent.com/84945537/144146526-f63ea50c-c0f0-4cde-9bcd-bcc07e271e1f.png)
