### ISSUE TITLE
Gerar Artes do Palestrantes da Grade

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#11]
### Peça/publicidade solicitada
Gerar Artes do Palestrantes da Grade

### Quais informações devem aparecer na arte

A princípio será um background que poderá ser reutilizado.
Nele deverá aparecer informações básicas como:

Data da conferência: 11 e 12 de Dezembro.
Link de inscrições: https://conf.scipy.lat/forms/formulario-participante/

Informações básicas da palestra:
    Nome do autor, avatar do autor, título da palestra.

Essa arte deverá poder ser compartilhada através de um link na grade do site.

Já foi realizado um trabalho anterior com isso, podemos forkar o projeto aqui:
https://github.com/GabrielRF/pybr2021-Arte-Palestrantes

### Data prevista para uso da arte
22/11/2021

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [?] Outro *(dúvida sobre o tamanho das imagens, melhor @lucenacam decidir)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre ScipyLat2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by arthuralvim** [comment]
Código feito. Falta parametrizar as artes.

**Comment by lucenacam** [comment]
![SciPy1](https://user-images.githubusercontent.com/84945537/144030239-8b10aa4f-5612-4975-943c-20f8c16f6f73.png)
![SciPy2](https://user-images.githubusercontent.com/84945537/144030243-6346eb19-c04d-4c88-8a1d-f3eaf0c68032.png)
![SciPy3](https://user-images.githubusercontent.com/84945537/144030471-2a8cebd8-e9af-437a-aa7e-30b681f2906d.png)

**Comment by arthuralvim** [comment]
Artes geradas. Estão em validação por @lucenacam, aguardando para serem postadas.
