### ISSUE TITLE
Atualizar Headers dos Formulários de Submissão de Atividades

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#16]
### Peça/publicidade solicitada
Atualizar Headers dos Formulários de Submissão de Atividades

### Quais informações devem aparecer na arte
Atualizar a data para 12 de novembro.

### Data prevista para uso da arte
04/11/2021

### Quais formatos necessários
- [ ] Quadrado
- [ ] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [ ] Formulários

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by lucenacam** [comment]
![Palestrantes_correção_en](https://user-images.githubusercontent.com/84945537/140430965-880d2d32-9fa0-40ee-8245-b1d0225dc46e.png)
![Palestrantes_correção_es](https://user-images.githubusercontent.com/84945537/140430969-36d654fd-6e13-440b-bce0-00ef0761915f.png)
![Palestrantes_correção_pt](https://user-images.githubusercontent.com/84945537/140430972-2a334890-690a-40e2-9fef-99013da64c41.png)

**Comment by arthuralvim** [comment]
Revisado e atualizado os formulários!
