### ISSUE TITLE
Juan Rodriguez -> Juan Luis Cano

### ISSUE THREAD

**Issue by astrojuanlu** [scipy-latinamerica/scipylat2021-org#19]
😇

**Comment by arthuralvim** [comment]
Going to change it in a bit.

**Comment by arthuralvim** [comment]
![Captura de Tela 2021-11-30 às 09 44 10](https://user-images.githubusercontent.com/812020/144049514-8d502321-c5ec-40e9-b0e3-8369b5c0acdb.png)

Done.
