### ISSUE TITLE
[Reunião] Medidas para Aumentar Engajamento das Palestras e Tutoriais: 30/10/2021

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#2]
# [Reunião] Medidas para Aumentar Engajamento das Palestras e Tutoriais

- Data: 30/10/2021
- Invite:

Scipy Latam Conference Meeting
Saturday, October 30 · 12:30 – 1:30pm
Google Meet joining info
Video call link: https://meet.google.com/kbv-uyeb-hfa
Or dial: ‪(BR) +55 11 3957-8605‬ PIN: ‪473 197 004‬#
More phone numbers: https://tel.meet/kbv-uyeb-hfa?pin=7938877846367

- Participantes:
  - Arthur Alvim (@arthuralvim)
  - Marcel Caraciolo (@marcelcaraciolo)
  - Camylle Lucena (@lucenacam)

## Acompanhamento das tarefas

- [ ] Verificar [tarefas bloqueadas](https://github.com/scipy-latinamerica/scipylat2021-org/projects/1?card_filter_query=label%3Abloqueado):
  - Está claro o que precisa ser feito para desbloquear a tarefa?
  - Há parte da tarefa que pode prosseguir de alguma forma?
- [ ] Verificar [tarefas em andamento](https://github.com/scipy-latinamerica/scipylat2021-org/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+-label%3ABloqueado+project%3Ascipy-latinamerica%2Fscipylat2021-org%2F1+), filtrando as bloqueadas e ordenando pela últimas que foram atualizadas.
  - A tarefa está associada a uma pessoa responsável?
  - Há algo bloqueando o avanço da tarefa que possa ser discutido?
- [ ] Verificar [tarefas abertas](https://github.com/scipy-latinamerica/scipylat2021-org/issues?q=is%3Aissue+is%3Aopen+project%3Ascipy-latinamerica%2Fscipylat2021-org%2F1+) não associadas ao projeto no Github.

## Ata

_Adicione os itens que foram discutidos durante a reunião._

-  Foco na divulgação do projeto em comunidades de data-science
-  Artes de divulgação :  Oque é o Scipy, Palestrantes Keynotes, Venha Participar
-  Abordar pelo menos 20 grupos até dia 10 de novembro
-  Itens do evento: Vídeo, hosting, slides, etc.

### Ações para serem realizadas

- Atividade (@responsável) - #issue

**Comment by marcelcaraciolo** [comment]
@arthuralvim  divulgado no linkedin evidencia:

https://www.linkedin.com/posts/marcelcaraciolo_la-octava-conferencia-cient%C3%ADfica-latinoamericana-activity-6863469665541242880-eFef
