### ISSUE TITLE
Divulgação 1-1 (convite palestrantes e referencias scipy)

### ISSUE THREAD

**Issue by marcelcaraciolo** [scipy-latinamerica/scipylat2021-org#4]
- [ ]   - Criar spreadsheed com os leads:
            nome, email, rede social, evento, já enviou o convite      
- [ ] - Escrever modelo email (pt/es)
- [ ]  - Escrever modelo instagram/linkedin/twitter (pt/es)
- [ ]  - Enviar a submissão para todos

**Comment by arthuralvim** [comment]
Acompanhando a issue. Vi que já adicionasse alguns contatos lá na spreadsheet @marcelcaraciolo .

Chegasse a caminhar algo do texto do template de email?

**Comment by arthuralvim** [comment]
Link da Planilha:

https://docs.google.com/spreadsheets/d/1l4TFjlA_IDHkPVKj5gZnDmKpybNHvoZcP4cjU-ky00A/edit

**Comment by lacerdamarcelo** [comment]
Oi pessoal,

Seria legal ter uma versão em inglês do email para que eu possa pedir para meu ex-orientador divulgar nas redes latinas dele. Eu posso traduzir a versão que vocês criarem em pt.

**Comment by arthuralvim** [comment]
Resolvido.
