### ISSUE TITLE
Substituir Header do Youtube e do Linkedin

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#5]
Substituir Header do Youtube e do Linkedin

### Detalhamento do uso
Substituir a imagem abaixo no Youtube corrigindo as datas do evento:

<img width="1193" alt="Captura de Tela 2021-10-30 às 13 44 45" src="https://user-images.githubusercontent.com/812020/139541833-313d2f8f-bec5-427b-8b67-0b1979c0fc5c.png">

E substituir a imagem a seguir da mesma forma.

### Quais informações devem aparecer na arte
Modificar as datas de 13 e 14 de Novembro para 11 e 12 de Dezembro.
Adicionar site do evento: https://conf.scipy.lat
Para o Linkedin adicionar redes sociais como no header anterior.

### Quais formatos necessários
- [x] Header do Youtube
- [x] Header do Linkedin: 1128px x 191px

### Locais para divulgação
- [x] Youtube
- [x] Linkedin

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by arthuralvim** [comment]
Adicionando a capa que Camylle me passou.
![Capa do Youtube](https://user-images.githubusercontent.com/812020/140000041-29e130b8-8da2-4c28-b3fb-dbdf6219931e.png)

**Comment by arthuralvim** [comment]
Eu já substitui lá no Youtube.

Eu gostava da imagem anterior, pensei que a gente só ia adicionar os dados faltantes.
Vamos tentar reutizá-la depois.

**Comment by lucenacam** [comment]
![Capa do Youtube](https://user-images.githubusercontent.com/84945537/140427484-529ed5d2-3bf1-41f4-a064-5a138cbac552.png)

**Comment by lucenacam** [comment]
![Capa do Youtube](https://user-images.githubusercontent.com/84945537/140429551-d9454f3d-1ae0-44d7-9c6b-77336c13c1cf.png)

**Comment by marcelcaraciolo** [comment]
@arthuralvim nao tenho poder de trocar no linkedin, so tu como admin!

**Comment by marcelcaraciolo** [comment]
@arthuralvim  trocado

https://www.linkedin.com/company/35641746/admin/

**Comment by arthuralvim** [comment]
Atualizado teu nível lá no Linkedin. Agora pode tudo!
