### ISSUE TITLE
Banner do evento

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#6]
### Campanha
Divulgação 1-1

### Peça/publicidade solicitada
Esse banner vai ser usado como cabeçalho para compor os emails que serão enviados como convites de palestras.
Utilizaremos as mesmas informações e mudaremos o formato para enviar como direct no instagram e twitter.

### Detalhamento do uso
*Descreva em detalhe para que essa arte será usada, exemplo: arte para divulgação dos tipos das atividades do evento, deverá existir um cartão para cada tipo*

### Data prevista para uso da arte
*Informe a data ou período previsto para uso da arte*

### Quais informações devem aparecer na arte
- Logo do evento com o texto a seguir: Scipy Latin America Conference 2021
- December 11th & 12th. 
- https://conf.scipy.lat
- 2 Background do Recife.

### Quais formatos necessários
- [x] Quadrado
- [ ] 640px x 320px

### Locais para divulgação
- [ ] Direct nas Redes sociais (twitter, facebook e instagram);
- [x] E-mail;

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by arthuralvim** [comment]
![Capa do Youtube](https://user-images.githubusercontent.com/812020/139999969-9c159347-a4df-4583-85e8-fa7c70581c07.png)

**Comment by lucenacam** [comment]
![Divulgação_evento_pt](https://user-images.githubusercontent.com/84945537/140188036-c3c78b36-f44e-4140-a7d5-f8eacf034610.png)
![Divulgação_evento](https://user-images.githubusercontent.com/84945537/140188056-e63070b7-5ebe-4a18-9dde-4ec9c040e6e9.png)

**Comment by lucenacam** [comment]
![Header_email](https://user-images.githubusercontent.com/84945537/140426366-a8b0ae35-1ecd-455a-80c5-7187615eca29.png)

**Comment by lucenacam** [comment]
![Header_email](https://user-images.githubusercontent.com/84945537/140429633-91eec490-fd23-41ab-9d12-2789ae4d3d58.png)

**Comment by lucenacam** [comment]
![Header_en](https://user-images.githubusercontent.com/84945537/140436416-14233ab7-6eeb-4380-8e90-185348f16883.png)
![Header_es](https://user-images.githubusercontent.com/84945537/140436431-8dd40f57-762d-4835-a967-78f5573438ac.png)
