### ISSUE TITLE
Artes para Divulgação da Keynote: Gigi Lucena

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#7]
### Campanha
Artes para Divulgação da Keynote: Gigi Lucena

### Peça/publicidade solicitada
Chamada de nova keynote no site e nas redes sociais.

### Detalhamento do uso
Precisamos das informações da keynote:
Nome de Divulgação, pequena bio, cargo, redes sociais.
Além disso precisamos das imagens para o site e postagens do twitter, instagram e facebook.

### Data prevista para uso da arte
03/11/2021

### Quais informações devem aparecer na arte
Seguir modelos das artes anteriores.

### Quais formatos necessários
- [ ] Quadrado
- [ ] Quadrado (telegram)
- [ ] Retangular (instagram story)

### Locais para divulgação
- [ x ] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord;
- [ x ] Grupos do Telegram;

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by lucenacam** [comment]
![Gigi_1](https://user-images.githubusercontent.com/84945537/140191104-fe220899-4565-481a-af90-5d55252460ff.png)

**Comment by lucenacam** [comment]
![Gigi_3](https://user-images.githubusercontent.com/84945537/140196010-ee50d4c7-7d41-4800-8fd0-5623607d6853.png)
![Gigi_4](https://user-images.githubusercontent.com/84945537/140196014-ef83460a-fc64-4816-8fc2-fb651801a0ea.png)

**Comment by arthuralvim** [comment]
avatares de Gigi
![Gigi_Hover](https://user-images.githubusercontent.com/812020/140235017-d40cdf81-8d7c-4d5a-91ed-e22e11fe8a0c.png)
![Gigi_Active](https://user-images.githubusercontent.com/812020/140235021-81edb6f9-f9df-48ce-aca5-569083c5d8c8.png)

**Comment by lucenacam** [comment]
Textos Gigi:

PT/BR:

Gigi é uma desenvolvedora de softwares na NASA no laboratório para lançamento de foguetes na Califórnia. Anteriormente, Gigi trabalhou como desenvolvedora de software na Unit Software no Brasil, liderando por 4 anos um time de 7 pessoas. Ela possui um bacharelado em ciências da computação pela CSUN e atualmente, é mestranda em robótica pelo instituto GATECH. Na NASA, ela trabalhou em missões como Marte (2020). Mãe de Davi, ela também trabalha como voluntária na área de educação, através de palestras sobre código e sua experiência na NASA com o objetivo de estimular crianças a aprimorarem seus conhecimentos. 

EN:

Gigi is a software engineer at NASA -Jet Propulsion Laboratory in California. Previously, Gigi worked as a software developer at Unit Software in Brazil for 8 years leading a team of 7 people in 4 years. Gigi has an AS in computer programming at SM college, a BS in computer science at CSUN and today she is working on her masters degree in robotics at GATECH Institute of Technology. At NASA, she worked in missions like Mars 2020. Mother of Davi, she also work as a volunteer on the education area through lectures about coding and her experience on NASA to help Brazilian children improve their skills.

**Comment by lucenacam** [comment]
![Gigi_3](https://user-images.githubusercontent.com/84945537/140429132-3df365df-6b62-427a-b4ea-92a1073e525e.png)
![Gigi_4](https://user-images.githubusercontent.com/84945537/140429138-447e994e-0e0c-47df-8213-8ec8856d2495.png)

**Comment by arthuralvim** [comment]
PT/BR:

Gigi é uma desenvolvedora de software no laboratório para lançamento de foguetes da NASA. Anteriormente, ela trabalhou como desenvolvedora de software na Unit Software no Brasil, liderando por 4 anos um time de 7 pessoas. Ela possui um bacharelado em ciências da computação pela CSUN e atualmente, é mestranda em robótica pelo instituto GATECH. Na NASA, ela trabalhou em missões como Marte (2020). Mãe de Davi, ela também trabalha como voluntária na área de educação, através de palestras sobre código e sua experiência na NASA com o objetivo de estimular crianças a aprimorarem seus conhecimentos.

EN:
Gigi is a software developer at NASA - Jet Propulsion Laboratory. Previously, she worked as a software developer at Unit Software in Brazil, leading a team of 7 people for 4 years. She holds a bachelor's degree in computer science from CSUN and is currently a master's student in robotics at GATECH institute. At NASA, she worked on missions like Mars (2020). Mother of Davi, she also works as a volunteer in the area of education, through lectures on code and her experience at NASA in order to encourage children to improve their knowledge.

ES:
Gigi es una desarrolladora de software en el Laboratorio de Lanzamiento de Cohetes de la NASA. Anteriormente, trabajó como desarrolladora de software en Unit Software en Brasil, liderando un equipo de 7 personas durante 4 años. Tiene una licenciatura en informática de CSUN y actualmente es estudiante de maestría en robótica del instituto GATECH. En la NASA, trabajó en misiones como Marte (2020). Madre de David, también trabaja como voluntaria en el área de educación, a través de conferencias sobre código y su experiencia en la NASA con el fin de animar a los niños a mejorar sus conocimientos.

**Comment by lucenacam** [comment]
![Gigi_2](https://user-images.githubusercontent.com/84945537/140431107-03607452-adc8-44af-8d16-605493313306.png)

**Comment by lucenacam** [comment]
![Gigi_2](https://user-images.githubusercontent.com/84945537/140436725-4a117ed4-4f68-4325-9970-7f924d7c6e05.png)
![Gigi_3](https://user-images.githubusercontent.com/84945537/140436729-0103a53b-d7ba-4a9d-ad36-bb7bb92f99c3.png)
![Gigi_4](https://user-images.githubusercontent.com/84945537/140436746-297e64ba-ee0e-4c73-b5f5-87351c9e3ecd.png)

**Comment by lucenacam** [comment]
![Stories_Gigi](https://user-images.githubusercontent.com/84945537/140437163-fe2e7795-49d4-4480-b0c2-cc0121a62389.png)

**Comment by arthuralvim** [comment]
Postagens agendadas!
