### ISSUE TITLE
Postagem Sobre Extensão do Prazo de Submissão

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#8]
### Peça/publicidade solicitada

Será um post para informar que o prazo de submissões foi estendido para  12/Novembro.

### Quais informações devem aparecer na arte
*Informe as informações que você imagina que deva conter na arte*

(pt-br)

- Prazo de envio de atividades estendido.
- 12/11/2021
- https://conf.scipy.lat/

- TEXTO DAS POSTAGENS: 

Queremos informar que o prazo para submissão de atividades foi estendido até o dia 12 de Novembro de 2021. 
Trabalha com Python científico e gostaria de mostrar seu trabalho/projeto? Você pode realizar a submissão de palestras através deste link: https://conf.scipy.lat/forms/formulario-palestrante/

------------
(es)

- Plazo de envío de actividades extendido.
- 12/11/2021
- https://conf.scipy.lat/es/
- TEXTO DAS POSTAGENS: 

Nos gustaría informarles que el plazo de envío de actividades se ha ampliado hasta el 12 de noviembre de 2021.
¿Trabajas con Python científico y te gustaría mostrar tu trabajo / proyecto? Puede enviar charlas a través de este enlace: https://conf.scipy.lat/es/forms/formulario-orador/

### Data prevista para uso da arte

-> 02/11/2021

### Quais formatos necessários
- [x] Quadrado
- [x] Retangular (instagram story)
- [ ] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord;
- [x] Grupos do Telegram;

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by lucenacam** [comment]
ES
![Instagram_estendido](https://user-images.githubusercontent.com/84945537/139908671-d7123941-9f42-4e4b-b772-e52770eaba71.png)
![Stories_estendido](https://user-images.githubusercontent.com/84945537/139908675-b31193fc-a8cc-4b64-8ff3-3acec58d1dc1.png)

**Comment by lucenacam** [comment]
PT/BR

![Instagram_estendido_pt](https://user-images.githubusercontent.com/84945537/139908778-e0594164-28d7-4458-b352-6d19220dd052.png)
![Stories_estendido_pt](https://user-images.githubusercontent.com/84945537/139908801-e05077c0-c5c7-49bd-a9a2-42536289066c.png)

**Comment by arthuralvim** [comment]
https://twitter.com/ScipyLA/status/1456055676439089154
https://twitter.com/ScipyLA/status/1456054821736288256
