### ISSUE TITLE
Postagem de Encerramento do Prazo de Submissões

### ISSUE THREAD

**Issue by arthuralvim** [scipy-latinamerica/scipylat2021-org#9]
### Peça/publicidade solicitada
Postagem de Encerramento do Prazo de Submissões

### Quais informações devem aparecer na arte
(pt)
- Prazo para submissões de atividades Encerrado!
- https://conf.scipy.lat/

TEXTO DAS POSTAGENS:

Obrigado a todos que enviaram as atividades! Os autores serão informados por email se sua proposta irá compor a grade de programação até o dia 22/11/2021. Até lá!

(es)
- ¡La fecha límite para el envío de actividades está cerrada!
- https://conf.scipy.lat/

TEXTO DAS POSTAGENS:
¡Gracias a todos los que enviaron las actividades! Se informará a los autores por correo electrónico si su propuesta se incluirá en el calendario hasta el 22/11/2021. ¡Hasta allá!

### Data prevista para uso da arte
12/11/2021

### Quais formatos necessários
- [x] Quadrado
- [x] Retangular (instagram story)
- [] Outro *(detalhe o formato necessário)*

### Locais para divulgação
- [x] Redes sociais (twitter, facebook e instagram);
- [ ] E-mail;
- [ ] Discord;
- [x] Grupos do Telegram;
- [ ] Eventos locais (Brasil + América Latina) (pedir 5min para falar sobre ScipyLat2021)

> Ferramenta para verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/) em imagens.

**Para concluir essa atividade, comente com os links dos posts realizados nas redes sociais ou prints, quando divulgação realizada em outros meios**

**Comment by lucenacam** [comment]
![Instagram_inscricoes_encerradas](https://user-images.githubusercontent.com/84945537/141381518-bd09c17f-6e8c-41c7-a0fa-0ac2fd522238.png)
![Stories_inscricoes_encerradas](https://user-images.githubusercontent.com/84945537/141381526-711a4d54-5a4f-4244-9619-f10e65fa1a80.png)

**Comment by lucenacam** [comment]
![Instagram_encerrado_pt](https://user-images.githubusercontent.com/84945537/141384867-73b86849-3d6b-4b11-97e7-443caf350ac6.png)
![Stories_encerrado_pt](https://user-images.githubusercontent.com/84945537/141384880-46dd33e8-e809-499b-8807-669b1c5972fc.png)

**Comment by lucenacam** [comment]
![Instagram_inscricoes_encerradas](https://user-images.githubusercontent.com/84945537/141529773-36ed724d-89f0-44f7-ba67-e2139644db5c.png)
![Stories_inscricoes_encerradas](https://user-images.githubusercontent.com/84945537/141529777-f7d337e4-d656-4f74-a81c-d505f40beaad.png)

**Comment by lucenacam** [comment]
![Instagram_encerrado_pt](https://user-images.githubusercontent.com/84945537/141529829-e9ebee4a-9c1e-43e6-8a25-dd424ece3c20.png)
![Stories_encerrado_pt](https://user-images.githubusercontent.com/84945537/141529833-1c45a71b-351f-40c0-82dc-08dcbbd3b124.png)

**Comment by arthuralvim** [comment]
Postagens programadas pra 0:00.

**Comment by arthuralvim** [comment]
Acho que só o texto em português que ficou estranho:

Ali era para ser "Envio de Propostas Encerrado"

**Comment by lucenacam** [comment]
![Instagram_encerrado_pt](https://user-images.githubusercontent.com/84945537/141602530-60b2ed1f-8a3b-4477-9572-67add7c32253.png)
![Stories_encerrado_pt](https://user-images.githubusercontent.com/84945537/141602534-900a4ae5-9c63-43d4-ac08-af581e2301f5.png)

**Comment by arthuralvim** [comment]
Resolvido.
